### ISSUE TITLE
Проверить доп. задание 5: отсортировано или нет

### ISSUE THREAD

**Issue by Lagunov-PRO** [Lagunov-PRO/ET05_Sorted_or_not#1]
@coursar
https://github.com/Lagunov-PRO/ET05_Sorted_or_not/blob/c58e74f01ecddc01b070c8ec9a4d4de619ef1bf0/app/lib.py#L12-L17

**Comment by coursar** [comment]
как сделать в одну строку?

**Comment by Lagunov-PRO** [comment]
@coursar 
Всё ещё в три:
```python
    for i in range(len(list_to_check) - 1):
        if list_to_check[i] > list_to_check[i + 1]: return False

    return True
```

**Comment by coursar** [comment]
нет )) что если просто сравнить через оператор `==` два списка?

**Comment by Lagunov-PRO** [comment]
@coursar 
Ещё раз его сортировать, только чтобы проверить, что он уже отсортирован? 
‘’’python
return your_list == sorted(your_list)
‘’’

**Comment by coursar** [comment]
почему нет? )) вопрос ведь в величине списка, если он не большой, то можно и отсортировать и по коду это будет на порядок быстрее. а потом уже смотреть, если он будет "расти" - будете оптимизировать

**Comment by Lagunov-PRO** [comment]
@coursar 
Ранняя оптимизация — зло? К это мы вы ведёте?
